# Some tips, tricks, and more


Mario Fiorino


## Flagged in cyclical way


In [ ]:
contatore = 0
colori = ["rosso", "verde", "nero", "giallo"]

for i in range(0,14):
    print(i)
    print(colori[contatore % 4])  # scrolls in cyclical way over the 4 colors in the list
    contatore += 1

    # NOTE
    ### The % symbol in Python is called the modulus operator and returns the remainder of division

0
rosso
1
verde
2
nero
3
giallo
4
rosso
5
verde
6
nero
7
giallo
8
rosso
9
verde
10
nero
11
giallo
12
rosso
13
verde


##Quickly build a matrix

In [ ]:
import random

row= 5
col = 6
matrix = [[random.randint(0, 9)] * col for _ in range(row)]
#print(matrix)

for i in range(len(matrix)):
    print("")
    for j in range(len(matrix[0])):
      print(matrix[i][j], end=" ")


7 7 7 7 7 7 
6 6 6 6 6 6 
4 4 4 4 4 4 
5 5 5 5 5 5 
1 1 1 1 1 1 

## Nested List Comprehensions: A Deeper Look

In [ ]:
fruits = [1,2,3,4,5,6]

newlist = [x  for x in fruits if x<2]
print(newlist)
newlist = [sum([x + a for x in fruits if x<2]) for a in range(999,1003)]
print(newlist)

print("\n *** \n")

newlist = [x  for x in fruits if x<3]
print(newlist)
newlist = [sum([x + a for x in fruits if x<3]) for a in range(999,1003)]
print(newlist) #out : [2001, 2003, 2005, 2007]:  how it works?
# for a=999 :  (x=1 the process : 999+1 )  +  (x=2 the process : 999+2) = 2001
# for a=1000:  (x=1 the process : 1000+1 )  +  (x=2 the process : 1000+2) = 2003
#...
# for a=1003:  (x=1 the process : 1003+1 )  +  (x=2 the process : 1003+2) = 2007

[1]
[1000, 1001, 1002, 1003]

 *** 

[1, 2]
[2001, 2003, 2005, 2007]


In [ ]:
#Equivalent

fruits = [1,2,3,4,5,6]

k = []
for a in range(999,1003):
  m = []
  for x in fruits:
    if x<3:
      m.append(x+a)
    else:
      break
  print("Auxiliary array : ",m)
  k.append(sum(m))

print("\n")
print(k)
print(newlist==k)

Auxiliary array :  [1000, 1001]
Auxiliary array :  [1001, 1002]
Auxiliary array :  [1002, 1003]
Auxiliary array :  [1003, 1004]


[2001, 2003, 2005, 2007]
True


##Find the path in a 2D-Grid

In [ ]:
def find_paths(matrix, start, end, max_steps):
    directions = {'right': (0, 1), 'left': (0, -1), 'up': (-1, 0), 'down': (1, 0)}
    paths = []
    def explore(x, y, steps, path):
        if steps > max_steps or x < 0 or y < 0 or x >= len(matrix) or y >= len(matrix[0]):
            return
        if [x, y] == end and steps <= max_steps:
            paths.append(path)
            return
        for direction, (dx, dy) in directions.items():
            explore(x + dx, y + dy, steps + 1, path + [direction])
    explore(start[0], start[1], 0, [])
    return paths

# Grid
row= 5
col = 5
matrix = [[0] * col for _ in range(row)]
#print(matrix)


#Example
max_steps = 3
dest_x = 4
dest_y = 2
end_point = [dest_x, dest_y]

x = 4
y = 3
start_point = [x, y]

paths = find_paths(matrix, start_point, end_point, max_steps)
total_paths = len(paths)

print(paths)

[['right', 'left', 'left'], ['left'], ['up', 'left', 'down'], ['up', 'down', 'left']]


##Edit a dict while preserving a copy of the original

In [ ]:
# Can do it better

originalDict = {1: "A", 2: "B", 3: ["a", "b"]}
print(originalDict)

def de(k = originalDict):
  print("  IN k= " ,k )
  k[1]= "$t€a££i"
  k[3][0]=999
  print("  OUT k= " ,k )

de()
print(originalDict)

{1: 'A', 2: 'B', 3: ['a', 'b']}
  IN k=  {1: 'A', 2: 'B', 3: ['a', 'b']}
  OUT k=  {1: '$t€a££i', 2: 'B', 3: [999, 'b']}
{1: '$t€a££i', 2: 'B', 3: [999, 'b']}


In [ ]:
# Can do it better

import copy

originalDict = {1: "A", 2: "B", 3: ["a", "b"]}
print(originalDict)

def de(k = originalDict.copy()):
  print("  IN k= " ,k )
  k[1]= "$t€a£i"
  k[3][0]=999
  print("  OUT k= " ,k )

de()
print(originalDict)

{1: 'A', 2: 'B', 3: ['a', 'b']}
  IN k=  {1: 'A', 2: 'B', 3: ['a', 'b']}
  OUT k=  {1: '$t€a£i', 2: 'B', 3: [999, 'b']}
{1: 'A', 2: 'B', 3: [999, 'b']}


In [ ]:
originalDict = {1: "A", 2: "B", 3: ["a", "b"]}
print(originalDict)

def de(k = copy.deepcopy(originalDict)):
  print("  IN k= " ,k )
  k[1]= "$t€a£i"
  k[3][0]=999
  print("  OUT k= " ,k )

de()
print(originalDict)

{1: 'A', 2: 'B', 3: ['a', 'b']}
  IN k=  {1: 'A', 2: 'B', 3: ['a', 'b']}
  OUT k=  {1: '$t€a£i', 2: 'B', 3: [999, 'b']}
{1: 'A', 2: 'B', 3: ['a', 'b']}


## Convert a String List to an Float List

In [ ]:
f = '[0. 0. 0. 3.5 0. 0. 1. 0. 7890.]'
print(f)
print(type(f))

h = f[1:-1].split(" ")
print(h)
print(type(h))

h = [float(x) for x in h]
print(h)
print(h[3])
print(type(h[3]))

[0. 0. 0. 3.5 0. 0. 1. 0. 7890.]
<class 'str'>
['0.', '0.', '0.', '3.5', '0.', '0.', '1.', '0.', '7890.']
<class 'list'>
[0.0, 0.0, 0.0, 3.5, 0.0, 0.0, 1.0, 0.0, 7890.0]
3.5
<class 'float'>


## Seed() -- Can I generate the same random numbers at the beginning of every Python code?

The seed() method  is used to initialize the pseudo-random number generator of Python which generates the random values

The random module provides a fast pseudorandom number generator based on the Mersenne Twister algorithm.

The pseudo-random number generator needs a number to start with (a seed value), to be able to generate a random number.

Seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines

By default the random number generator uses the current system time.You can use the seed() method to customize the start number of the random number generator.



In [ ]:
import random

# If you use the same seed value twice you will get the same sequence of random numbers twice.
random.seed(123)
print(random.random())
print(random.random())
print(random.random())
print("**")
random.seed(123)
print(random.random())
print(random.random())
print(random.random())
print("**")
random.seed(0)
print(random.random())
print(random.random())
print(random.random())

0.052363598850944326
0.08718667752263232
0.4072417636703983
**
0.052363598850944326
0.08718667752263232
0.4072417636703983
**
0.8444218515250481
0.7579544029403025
0.420571580830845


##Variables in Python

Python is an object-oriented language.

Everything in Python is an object.

A Python Variable is a symbolic name that is a reference to an object. Once an object is assigned to a variable, you can refer to the object by that name.

*


When an object has no longer any reference to, it is orphaned, and there is no way to access it.
The life cycle of an object initiates upon its creation, establishing at least one reference to it. An object remains 'alive' as long as there exists at least one reference to it.

When the count of references to an object is zero, it becomes unreachable, signaling the end of its life. Python automatically detects such inaccessible objects and reclaims the memory they occupy, making it available for other purposes. This process is commonly known as garbage collection in computer scince.

*


id()

In Python, upon creation, every object is assigned a number that uniquely identifies it.

It is guaranteed that no two objects will share the same identifier while their lifetimes.


$\;$

More info :

https://realpython.com/python-variables/



In [ ]:
#Informally, in Pytohn you can think of a variable as a "nickname" you give to an area of memory.

s = 1
d = s
# With instruction d = s, Python does not create another object.
# Instead, it creates a new symbolic name or reference, "d" ,
# which points to the same object that "s" points to. This memory optimization enhances efficiency.
print("s=",s, "@@ id=", id(s))
print("d=",d, "@@ id=", id(d))
print("")


s = s + 98
print("s=",s, "@@ id=", id(s))
print("d=",d, "@@ id=", id(d))
print("")


s = "Yes!"
print("s=",s, "@@ id=", id(s))
print("d=",d, "@@ id=", id(d))
print(s==d)
print(s is d)
print("")


d = 257
s = 257
print("s=",s, "@@ id=", id(s))
print("d=",d, "@@ id=", id(d))
print(s==d)
print(s is d)
print("")


d = 256
s = 256
print("s=",s, "@@ id=", id(s))
print("d=",d, "@@ id=", id(d))
print(s==d)
print(s is d)
# Python interpreter optimizes performance for small integers.
# When you create an int in that range [-5, 256] you actually just get back a reference to the existing object.
# This means that assigning separate variables to values in this range will make them refer
# to the same underlying object, not creating new ones each time.
print("")

s= 1 @@ id= 134462169612528
d= 1 @@ id= 134462169612528

s= 99 @@ id= 134462169615664
d= 1 @@ id= 134462169612528

s= Yes! @@ id= 134461059737008
d= 1 @@ id= 134462169612528
False
False

s= 257 @@ id= 134461059991568
d= 257 @@ id= 134461059994000
True
False

s= 256 @@ id= 134462169620688
d= 256 @@ id= 134462169620688
True
True



## print() v.s. repr()

In [ ]:
import numpy as np
import datetime

l = "Hello 123 "
print(repr(l))  # repr() prints an “raw” representation of data
print(l)

value = np.ones(4)
print(repr(value))
print(value)

today = datetime.datetime.now()
print(repr(today))
print(today)

'Hello 123 '
Hello 123 
array([1., 1., 1., 1.])
[1. 1. 1. 1.]
datetime.datetime(2024, 1, 4, 12, 53, 43, 304582)
2024-01-04 12:53:43.304582


##np.random.choice()

In [ ]:
import numpy as np

n = 0
supp = [0, 1, 2]

a = np.random.choice(supp, p=[0.7, 0.25,  0.05]) # p= probability distribution

print(a)

0


##np.linspace()

In [ ]:
x = np.linspace(-1, 5, 10)
print(x)

[-1.         -0.33333333  0.33333333  1.          1.66666667  2.33333333
  3.          3.66666667  4.33333333  5.        ]


## To check if one number is equal to or greater than twice the other and vice versa

In [ ]:
def e_il_doppio(x, y):
    if y ==0 or x ==0 :
      return ("Error")
    return x / y >= 2 or y / x >= 2

x = 30
y = 70

print(e_il_doppio(x, y))

True


##Find if there is at least one element greater than zero in a np.matrix

In [ ]:
import numpy as np

Q = np.zeros((5, 5)).round(3)

Q[1][2] = 0.001
Q[4][0] = 0.001

if np.size(np.where(Q > 0)[0]) != 0:
  print("Find!")
  print("Indexes :", np.where(Q > 0))
  print("\n",Q,"\n")

  # Alternative, if just one element
  #row = int(np.where(Q > 0)[0])
  #col = int(np.where(Q > 0)[1])
  #print("It's in row: ", row,", column: ",col)


Find!
Indexes : (array([1, 4]), array([2, 0]))

 [[0.    0.    0.    0.    0.   ]
 [0.    0.    0.001 0.    0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.001 0.    0.    0.    0.   ]] 



## Find the maximum value in a dictionary

In [ ]:
d = {'a': 3, 'b': 2, 'c': 98, 'd': 3, 'e': 95, 'f': 1}

max_value = None

for value in d.values():
    if (max_value is None) or (value > max_value):
        max_value = value

print(max_value)

98
